63 add pre build script with linter

diff --git a/project.yml b/project.yml
--- a/project.yml
+++ b/project.yml
@@ -15,11 +15,21 @@ targets:
         settings:
             base:
                 PRODUCT_BUNDLE_IDENTIFIER: com.yandex.sirius.GoInvest
-#        dependencies:
-#        - framework: UIComponents.framework
         scheme:
             testTargets:
             - GoInvestTests
+        preBuildScripts:
+            - script: |
+                #!/bin/bash
+                # Swiftlint
+    
+                export PATH="$PATH:/opt/homebrew/bin"
+                if which swiftlint >/dev/null; then
+                    swiftlint lint --strict
+                else
+                    echo "error: SwiftLint does not exist, download it from https://github.com/realm/SwiftLint"
+                    exit 1
+                fi
     GoInvestTests:
         type: bundle.unit-test
         platform: iOS
