#HEAD #main fix 4 of swiftlint

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,21 +1,16 @@
-#export PATH="$PATH:/opt/homebrew/bin"
-#if which swiftlint >/dev/null; then
-#  swiftlint
-#else
-#  echo "error: SwiftLint does not exist, download it from https://github.com/realm/SwiftLint"
-#  exit 1
-#fi
-
-
 #!/bin/bash
 
 # Запускаем SwiftLint
+ 
+
 if which swiftlint > /dev/null; then
   # Проверяем наличие предупреждений
-  if ! swiftlint | grep -q "warning"; then
-    echo "No SwiftLint warnings found. Continuing with commit."
+  swiftlint --fix
+  if ! swiftlint | grep -q "warning" &&  ! swiftlint | grep -q "error"; then
+    echo "✅ Linting successed"
   else
-    echo "SwiftLint warnings found. Commit aborted."
+    swiftlint
+    echo "❌ SwiftLint warnings found. Commit aborted."
     exit 1  # Прерываем коммит
   fi
 else
